name: Notify Discord on new Issue

on:
  issues:
    types: ["opened"]


jobs:
  notify:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Tungdil83/discord-issue-notify@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_PEP_WEBHOOK_URL }}
          mention_users: ""
          mention_roles: ""
